# -*- coding: utf-8 -*-
"""decision_repository.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v_u3tNh4JZv55TRWATtN6jcXEOhR57yX
"""

from abc import ABC, abstractmethod
from typing import List, Optional

from app.domain.decision import Decision


class DecisionRepository(ABC):
    @abstractmethod
    def save(self, decision: Decision) -> Decision:
        pass

    @abstractmethod
    def get_by_id(self, decision_id: str) -> Optional[Decision]:
        pass

    @abstractmethod
    def list_all(self) -> List[Decision]:
        pass