# -*- coding: utf-8 -*-
"""in_memory_decision_repository.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11gqgvYm3PmOTGrqBPeh8U5utV_5X9Axa
"""

from typing import Dict, List, Optional

from app.domain.decision import Decision
from app.repositories.decision_repository import DecisionRepository


class InMemoryDecisionRepository(DecisionRepository):
    def __init__(self) -> None:
        self._decisions: Dict[str, Decision] = {}

    def save(self, decision: Decision) -> Decision:
        self._decisions[decision.id] = decision
        return decision

    def get_by_id(self, decision_id: str) -> Optional[Decision]:
        return self._decisions.get(decision_id)

    def list_all(self) -> List[Decision]:
        return list(self._decisions.values())