# -*- coding: utf-8 -*-
"""test_decision_service.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uf6YYZXwQPduiumrAAT1S4EQOKrhawYc
"""

from app.services.decision_service import DecisionService


def test_create_replenishment_decision_returns_decision():
    service = DecisionService()

    decision = service.create_replenishment_decision(
        product_id="P1001",
        business_objective="AvoidStockout",
        priority="high",
        time_horizon="30_days",
    )

    assert decision.id.startswith("DEC-")
    assert decision.decision_type.value == "inventory_replenishment"
    assert decision.context is not None
    assert decision.context.product_id == "P1001"
    assert decision.context.business_objective == "AvoidStockout"


def test_get_decision_returns_saved_decision():
    service = DecisionService()

    created = service.create_replenishment_decision(
        product_id="P1001",
        business_objective="AvoidStockout",
        priority="high",
        time_horizon="30_days",
    )

    fetched = service.get_decision(created.id)

    assert fetched is not None
    assert fetched.id == created.id


def test_list_decisions_returns_all_saved_decisions():
    service = DecisionService()

    service.create_replenishment_decision(
        product_id="P1001",
        business_objective="AvoidStockout",
        priority="high",
        time_horizon="30_days",
    )
    service.create_replenishment_decision(
        product_id="P1002",
        business_objective="MaintainServiceLevel",
        priority="medium",
        time_horizon="30_days",
    )

    decisions = service.list_decisions()

    assert len(decisions) == 2