import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function exportDecisionReport(decision) {
  const doc = new jsPDF();

  // ===========================
  // Header
  // ===========================

  doc.setFontSize(20);
  doc.setTextColor(37, 99, 235);
  doc.text("AI Decision Laboratory", 14, 20);

  doc.setFontSize(11);
  doc.setTextColor(100);
  doc.text("Decision Intelligence Platform", 14, 28);

  doc.setDrawColor(220);
  doc.line(14, 33, 196, 33);

  // ===========================
  // Decision Summary
  // ===========================

  autoTable(doc, {
    startY: 40,
    head: [["Decision Summary", ""]],
    body: [
      ["Decision ID", decision.decision_id],
      ["Decision Type", decision.decision_type],
      ["Status", decision.status],
    ],
    theme: "grid",
    headStyles: {
      fillColor: [37, 99, 235],
    },
  });

  // ===========================
  // Context
  // ===========================

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 10,
    head: [["Business Context", ""]],
    body: [
      [
        "Business Objective",
        decision.context?.business_objective || "-",
      ],
      [
        "Product ID",
        decision.context?.product_id || "-",
      ],
      [
        "Priority",
        decision.context?.priority || "-",
      ],
      [
        "Time Horizon",
        decision.context?.time_horizon || "-",
      ],
    ],
    theme: "grid",
    headStyles: {
      fillColor: [37, 99, 235],
    },
  });

  // ===========================
  // Selected Strategy
  // ===========================

  if (decision.selected_strategy) {
    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 10,
      head: [["Selected Strategy", ""]],
      body: [
        [
          "Strategy",
          decision.selected_strategy.name,
        ],
        [
          "Evaluation Score",
          Number(
            decision.selected_strategy.score
          ).toFixed(2),
        ],
        [
          "Description",
          decision.selected_strategy.description,
        ],
      ],
      theme: "grid",
      headStyles: {
        fillColor: [37, 99, 235],
      },
    });
  }

  // ===========================
  // Alternative Strategies
  // ===========================

  if (decision.strategies?.length > 0) {
    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 10,
      head: [["Alternative Strategy", "Score"]],
      body: decision.strategies.map((strategy) => [
        strategy.name,
        Number(strategy.score).toFixed(2),
      ]),
      theme: "striped",
      headStyles: {
        fillColor: [37, 99, 235],
      },
    });
  }

  // ===========================
  // Business Data
  // ===========================

  if (decision.context?.business_data) {
    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 10,
      head: [["Business Data", "Value"]],
      body: Object.entries(
        decision.context.business_data
      ),
      theme: "striped",
      headStyles: {
        fillColor: [37, 99, 235],
      },
    });
  }

  // ===========================
  // Footer
  // ===========================

  doc.setFontSize(10);
  doc.setTextColor(120);

  doc.text(
    "Generated by AI Decision Laboratory",
    14,
    285
  );

  doc.save(
    `Decision_${decision.decision_id}.pdf`
  );
}