# -*- coding: utf-8 -*-
"""decision_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/193o96Cm0A6ZomoVFQ4RsjGUGdx3TvoFw
"""

from app.domain.strategy import Strategy


class DecisionPipeline:
    def generate_strategies(self, current_stock: int) -> list[Strategy]:
        if current_stock < 100:
            return [
                Strategy(
                    id="S1",
                    name="Order Immediately",
                    description="Place a full replenishment order now.",
                    score=0.92,
                ),
                Strategy(
                    id="S2",
                    name="Partial Order",
                    description="Place a partial order to reduce stockout risk.",
                    score=0.84,
                ),
                Strategy(
                    id="S3",
                    name="Delay Order",
                    description="Wait and review demand before ordering.",
                    score=0.41,
                ),
            ]

        return [
            Strategy(
                id="S1",
                name="Maintain Stock",
                description="Current stock is sufficient, no immediate order needed.",
                score=0.88,
            ),
            Strategy(
                id="S2",
                name="Small Reorder",
                description="Place a small reorder to maintain safety stock.",
                score=0.73,
            ),
        ]

    def select_best_strategy(self, strategies: list[Strategy]) -> Strategy:
        return max(strategies, key=lambda s: s.score)