# -*- coding: utf-8 -*-
"""decision_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dvXAwIR2ciIhZaIT-oBWKaB0IXWCSXO2
"""

from __future__ import annotations

from app.domain.decision_context import DecisionContext
from app.domain.strategy import Strategy


class DecisionEngine:
    def generate_strategies(self, context: DecisionContext) -> list[Strategy]:
        current_stock = int(context.business_data.get("current_stock", 0))
        daily_sales = int(context.business_data.get("daily_sales", 0))
        supplier_lead_time = int(context.business_data.get("supplier_lead_time", 7))
        safety_stock = int(context.business_data.get("safety_stock", 50))
        unit_cost = float(context.business_data.get("unit_cost", 10.0))
        budget = float(context.business_data.get("budget", 10_000.0))

        demand_during_lead_time = daily_sales * supplier_lead_time
        target_quantity = max(0, (safety_stock + demand_during_lead_time) - current_stock)

        full_order_cost = target_quantity * unit_cost
        partial_order_cost = max(0, target_quantity // 2) * unit_cost

        if current_stock < safety_stock:
            return [
                Strategy(
                    id="S1",
                    name="Order Immediately",
                    description=f"Order {target_quantity} units now to avoid stockout risk.",
                    expected_impact={
                        "quantity": target_quantity,
                        "estimated_cost": full_order_cost,
                        "budget_ok": full_order_cost <= budget,
                        "stock_risk": "low",
                    },
                    score=0.95 if full_order_cost <= budget else 0.78,
                ),
                Strategy(
                    id="S2",
                    name="Partial Order",
                    description=f"Order about {max(1, target_quantity // 2)} units now and review later.",
                    expected_impact={
                        "quantity": max(1, target_quantity // 2),
                        "estimated_cost": partial_order_cost,
                        "budget_ok": partial_order_cost <= budget,
                        "stock_risk": "medium",
                    },
                    score=0.84,
                ),
                Strategy(
                    id="S3",
                    name="Delay Order",
                    description="Wait and monitor demand before placing the replenishment order.",
                    expected_impact={
                        "quantity": 0,
                        "estimated_cost": 0,
                        "budget_ok": True,
                        "stock_risk": "high",
                    },
                    score=0.41,
                ),
            ]

        return [
            Strategy(
                id="S1",
                name="Maintain Stock",
                description="Current stock is sufficient, so no immediate order is needed.",
                expected_impact={
                    "quantity": 0,
                    "estimated_cost": 0,
                    "budget_ok": True,
                    "stock_risk": "low",
                },
                score=0.90,
            ),
            Strategy(
                id="S2",
                name="Small Reorder",
                description="Place a small reorder to keep safety stock stable.",
                expected_impact={
                    "quantity": max(1, safety_stock - current_stock // 2),
                    "estimated_cost": max(1, safety_stock - current_stock // 2) * unit_cost,
                    "budget_ok": True,
                    "stock_risk": "low",
                },
                score=0.75,
            ),
        ]

    def select_best_strategy(self, strategies: list[Strategy]) -> Strategy:
        return max(strategies, key=lambda strategy: strategy.score)