# -*- coding: utf-8 -*-
"""explanation_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13cP0Oxw1JJ9xH9C6jah7kMBOkX0Wr4Zs
"""

from __future__ import annotations

from app.domain.decision_knowledge import DecisionKnowledge
from app.domain.recommendation import Recommendation


class ExplanationEngine:
    """
    Builds a human-readable explanation for the recommendation.
    """

    def explain(
        self,
        knowledge: DecisionKnowledge,
        recommendation: Recommendation,
    ) -> Recommendation:
        current_stock = knowledge.current_stock
        safety_stock = knowledge.safety_stock
        daily_sales = knowledge.daily_sales
        lead_time = knowledge.supplier_lead_time
        budget = knowledge.budget

        recommendation.add_explanation(
            f"Current stock is {current_stock}, while safety stock is {safety_stock}."
        )
        recommendation.add_explanation(
            f"Expected demand during lead time is about {daily_sales * lead_time} units."
        )
        recommendation.add_explanation(
            f"Available budget is {budget}, so the recommendation stays within budget."
        )
        recommendation.add_explanation(
            "The selected strategy achieved the highest evaluation score."
        )

        return recommendation