# -*- coding: utf-8 -*-
"""decision_knowledge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15MP05oqC-5ub22BkzdssMsW7n25RY6Yv
"""

from dataclasses import dataclass, field


@dataclass
class DecisionKnowledge:
    product_id: str
    business_objective: str
    priority: str
    time_horizon: str

    current_stock: int
    daily_sales: int
    supplier_lead_time: int
    safety_stock: int
    warehouse_capacity: int
    budget: float
    unit_cost: float

    constraints: list[str] = field(default_factory=list)
    policies: list[str] = field(default_factory=list)
    external_events: list[str] = field(default_factory=list)