# -*- coding: utf-8 -*-
"""decision_outcom.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O4jzGk6pKIc8YH--ulrUrqf269MRMbzf
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, UTC


@dataclass
class DecisionOutcome:
    """
    Represents the actual business outcome after
    implementing a recommendation.
    """

    implemented: bool = False

    actual_sales: int = 0

    remaining_inventory: int = 0

    stockout_occurred: bool = False

    recommendation_successful: bool = False

    notes: str = ""

    recorded_at: datetime = field(
        default_factory=lambda: datetime.now(UTC)
    )

    def mark_success(self) -> None:
        self.recommendation_successful = True

    def mark_failure(self) -> None:
        self.recommendation_successful = False