import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";

import Navigation from "../components/Navigation";
import { getDecisions } from "../services/api";

function DecisionHistory() {
  const navigate = useNavigate();

  const [decisions, setDecisions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    loadDecisions();
  }, []);

  const loadDecisions = async () => {
    try {
      setLoading(true);
      setError("");

      const response = await getDecisions();

      setDecisions(response.data);
    } catch (err) {
      console.error(err);
      setError("Failed to load decision history.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <Navigation />

      <div className="hero">
        <p className="eyebrow">Decision Intelligence</p>

        <h1>Decision History</h1>

        <p className="subtitle">
          Review all business decisions generated by the AI Decision
          Laboratory.
        </p>
      </div>

      <div className="card">

        {loading && <p>Loading decision history...</p>}

        {error && <p className="error">{error}</p>}

        {!loading && !error && (
          <div className="history-table">

            <div className="history-row history-header">
              <div>Decision ID</div>
              <div>Decision Type</div>
              <div>Status</div>
            </div>

            {decisions.length === 0 ? (
              <div className="history-row">
                <div>No decisions found.</div>
                <div>-</div>
                <div>-</div>
              </div>
            ) : (
              decisions.map((decision) => (
                <div
                  key={decision.decision_id}
                  className="history-row"
                  onClick={() =>
                    navigate(`/decision/${decision.decision_id}`)
                  }
                >
                  <div>{decision.decision_id}</div>

                  <div>{decision.decision_type}</div>

                  <div>
                    <span className="status completed">
                      {decision.status.toUpperCase()}
                    </span>
                  </div>
                </div>
              ))
            )}

          </div>
        )}

      </div>
    </>
  );
}

export default DecisionHistory;