import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { FaFileExcel } from "react-icons/fa";

import Navigation from "../components/Navigation";
import { getDecisions } from "../services/api";
import { exportDecisionHistory } from "../services/excelExport";
import "./DecisionHistory.css";

function DecisionHistory() {
  const navigate = useNavigate();

  const [decisions, setDecisions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");

  useEffect(() => {
    loadDecisions();
  }, []);

  const loadDecisions = async () => {
    try {
      setLoading(true);
      setError("");

      const response = await getDecisions();
      setDecisions(response.data);
    } catch (err) {
      console.error(err);
      setError("Failed to load decision history.");
    } finally {
      setLoading(false);
    }
  };

  const filteredDecisions = useMemo(() => {
    const query = searchQuery.trim().toLowerCase();

    return decisions.filter((decision) => {
      const decisionId = String(decision.decision_id || "").toLowerCase();
      const decisionType = String(decision.decision_type || "").toLowerCase();
      const status = String(decision.status || "").toLowerCase();

      const matchesSearch =
        query === "" ||
        decisionId.includes(query) ||
        decisionType.includes(query);

      const matchesStatus =
        statusFilter === "all" || status === statusFilter.toLowerCase();

      return matchesSearch && matchesStatus;
    });
  }, [decisions, searchQuery, statusFilter]);

  const completedCount = decisions.filter(
    (decision) => String(decision.status || "").toLowerCase() === "completed"
  ).length;

  return (
    <>
      <Navigation />

      <div className="hero">
        <p className="eyebrow">Decision Intelligence</p>

        <h1>Decision History</h1>

        <p className="subtitle">
          Review all business decisions generated by the AI Decision Laboratory.
        </p>
      </div>

      <div className="card">
        <div className="dashboard-section history-summary">
          <div className="analytics-grid">
            <div className="analytics-card">
              <h3>Total Decisions</h3>
              <p>{decisions.length}</p>
            </div>

            <div className="analytics-card">
              <h3>Showing</h3>
              <p>{filteredDecisions.length}</p>
            </div>

            <div className="analytics-card">
              <h3>Completed</h3>
              <p>{completedCount}</p>
            </div>

            <div className="analytics-card">
              <h3>Search Filter</h3>
              <p>{searchQuery.trim() || "None"}</p>
            </div>
          </div>
        </div>

        <div className="dashboard-section history-filters">
          <div className="analytics-grid">
            <div className="analytics-card">
              <label htmlFor="searchDecision" className="section-title">
                Search Decision
              </label>

              <input
                id="searchDecision"
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search by Decision ID or Type..."
                className="history-input"
              />
            </div>

            <div className="analytics-card">
              <label htmlFor="statusFilter" className="section-title">
                Status
              </label>

              <select
                id="statusFilter"
                value={statusFilter}
                onChange={(e) => setStatusFilter(e.target.value)}
                className="history-select"
              >
                <option value="all">All</option>
                <option value="completed">Completed</option>
                <option value="in_progress">In Progress</option>
                <option value="created">Created</option>
                <option value="cancelled">Cancelled</option>
              </select>
            </div>
          </div>
        </div>

        <div className="dashboard-section">
          <div className="history-toolbar">
            <button
              type="button"
              onClick={loadDecisions}
              className="refresh-button"
            >
              Refresh
            </button>

            {!loading && filteredDecisions.length > 0 && (
              <button
                type="button"
                className="export-button"
                onClick={() => exportDecisionHistory(filteredDecisions)}
              >
                <FaFileExcel />
                Export Excel
              </button>
            )}
          </div>

          {loading && <p>Loading decision history...</p>}

          {error && <p className="error">{error}</p>}

          {!loading && !error && (
            <div className="history-table">
              <div className="history-row history-header">
                <div>Decision ID</div>
                <div>Decision Type</div>
                <div>Status</div>
                <div>Action</div>
              </div>

              {filteredDecisions.length === 0 ? (
                <div className="history-row">
                  <div>No decisions found.</div>
                  <div>-</div>
                  <div>-</div>
                  <div>-</div>
                </div>
              ) : (
                filteredDecisions.map((decision) => (
                  <div key={decision.decision_id} className="history-row">
                    <div>{decision.decision_id}</div>

                    <div>{decision.decision_type}</div>

                    <div>
                      <span className="status completed">
                        {String(decision.status || "").toUpperCase()}
                      </span>
                    </div>

                    <div>
                      <button
                        type="button"
                        onClick={() =>
                          navigate(`/decision/${decision.decision_id}`)
                        }
                        className="view-button"
                      >
                        View
                      </button>
                    </div>
                  </div>
                ))
              )}
            </div>
          )}
        </div>
      </div>
    </>
  );
}

export default DecisionHistory;